#include "PortableLayout.h"

#include "../app/Paths.h"
#include "../platform/ProcessUtil.h"

#include <windows.h>

#include <algorithm>
#include <sstream>
#include <vector>

namespace {

// 注意: 判断 junction 不能用 std::filesystem::exists ——
//   * 断链的 junction: exists() == false, 但目录项确实占着名字,
//     此时 mklink 会报「已存在」, 必须先删。
//   * 更危险的是 remove_all(): 它会**递归进目标**把 data\ 里
//     真实数据删干净。对 junction 只能 RemoveDirectoryW (只删链接本身)。
bool entryExists(const fs::path& p) {
    return GetFileAttributesW(p.c_str()) != INVALID_FILE_ATTRIBUTES;
}

bool isReparsePoint(const fs::path& p) {
    DWORD a = GetFileAttributesW(p.c_str());
    return a != INVALID_FILE_ATTRIBUTES && (a & FILE_ATTRIBUTE_REPARSE_POINT) != 0;
}

bool isRealDirectory(const fs::path& p) {
    DWORD a = GetFileAttributesW(p.c_str());
    if (a == INVALID_FILE_ATTRIBUTES) return false;
    if ((a & FILE_ATTRIBUTE_REPARSE_POINT) != 0) return false;   // 是链接, 不算
    return (a & FILE_ATTRIBUTE_DIRECTORY) != 0;
}

bool dirIsEmpty(const fs::path& p) {
    std::error_code ec;
    return fs::directory_iterator(p, ec) == fs::directory_iterator();
}

// 只删目录项本身 (junction / 空目录), 绝不递归
bool removeEntryOnly(const fs::path& p) {
    if (RemoveDirectoryW(p.c_str())) return true;
    std::error_code ec;
    fs::remove(p, ec);
    return !ec;
}

fs::path comSpecPath() {
    wchar_t buf[MAX_PATH] = {0};
    DWORD n = GetEnvironmentVariableW(L"ComSpec", buf, MAX_PATH);
    if (n == 0 || n >= MAX_PATH) return L"C:\\Windows\\System32\\cmd.exe";
    return fs::path(std::wstring(buf, n));
}

bool resolvesTo(const fs::path& link, const fs::path& want) {
    std::error_code ec;
    fs::path a = fs::weakly_canonical(link, ec);
    if (ec || a.empty()) return false;
    std::error_code ec2;
    fs::path b = fs::weakly_canonical(want, ec2);
    if (ec2 || b.empty()) return false;
    return a == b;
}

} // namespace

namespace hs::portable {

bool ensureDataJunction(const fs::path& root, std::string* err) {
    if (root.empty()) {
        if (err) *err = "root 为空";
        return false;
    }
    std::error_code ec;
    const fs::path link   = root / "_home" / ".hermes";
    const fs::path target = root / "data";

    fs::create_directories(target, ec);
    fs::create_directories(link.parent_path(), ec);

    if (entryExists(link)) {
        if (isReparsePoint(link)) {
            if (resolvesTo(link, target)) return true;   // 已经对了, 什么都不做
            // 指向别处 —— 典型场景: 打包机是 D:\, 拷到 I:\ 就断了
            if (!removeEntryOnly(link)) {
                if (err) *err = "无法删除失效的 .hermes 链接: " + link.string();
                return false;
            }
        } else if (isRealDirectory(link)) {
            // 真实目录 (不是链接)。空则换成 junction; 非空说明用户数据在里面,
            // 原样保留 —— 宁可回到「数据落在 _home\.hermes」也不删数据。
            if (!dirIsEmpty(link)) return true;
            if (!removeEntryOnly(link)) return false;
        } else {
            fs::remove(link, ec);
        }
    }

    // junction 不需要管理员权限 (符号链接才需要), 但只能用 cmd 建
    proc::LaunchOptions opt;
    opt.exe    = comSpecPath();
    opt.args   = {"/c", "mklink", "/J", link.string(), target.string()};
    opt.hidden = true;

    std::string capErr;
    auto r = proc::runAndCapture(opt, 20000, &capErr);
    if (r.exitCode != 0 || !isReparsePoint(link)) {
        if (err) {
            *err = "mklink /J 失败 (exit=" + std::to_string(r.exitCode) + ")";
            if (!r.output.empty()) *err += ": " + r.output.substr(0, 300);
            else if (!capErr.empty()) *err += ": " + capErr;
        }
        return false;
    }
    return true;
}

bool ensureSandbox(const fs::path& root, std::string* err) {
    if (root.empty()) {
        if (err) *err = "root 为空";
        return false;
    }
    // 顺序关键: 先把目录建出来, 再有任何进程把它们当 TEMP/LOCALAPPDATA 用
    hs::Paths::createSandboxDirsAt(root);
    return ensureDataJunction(root, err);
}

std::string hermesBatScript() {
    std::ostringstream o;
    auto line = [&](const std::string& s) { o << s << "\r\n"; };

    line("@echo off");
    line("rem ============================================================");
    line("rem  Hermes Portable - Windows launcher (PURE ASCII ONLY)");
    line("rem");
    line("rem  Generated by AgentDock PortableBuilder.");
    line("rem");
    line("rem  This file MUST stay pure ASCII. cmd.exe parses .bat using the");
    line("rem  system ANSI codepage (GBK on a Chinese Windows); any non-ASCII");
    line("rem  byte - even inside a rem comment - can chop the line and turn");
    line("rem  the rest into garbage commands. Keep every comment in English.");
    line("rem");
    line("rem  What it does:");
    line("rem    1) create the in-package sandbox dirs (_home/...)");
    line("rem    2) hijack every env var that would otherwise resolve to the");
    line("rem       host user profile, so nothing is written outside the box");
    line("rem    3) absolutize venv/pyvenv.cfg home (the python-build-standalone");
    line("rem       trampoline resolves a relative home against the CWD)");
    line("rem    4) repair the _home\\.hermes junction after a move");
    line("rem    5) start web-ui via the bundled node");
    line("rem ============================================================");
    line("setlocal enabledelayedexpansion");
    line("");
    line("set \"HERE=%~dp0\"");
    line("if \"%HERE:~-1%\"==\"\\\" set \"HERE=%HERE:~0,-1%\"");
    line("cd /d \"%HERE%\"");
    line("");
    line("set \"SANDBOX=%HERE%\\_home\"");
    line("set \"DATA_DIR=%HERE%\\data\"");
    line("set \"PY_BASE=%HERE%\\python\\base\"");
    line("set \"VENV_DIR=%HERE%\\python\\venv\"");
    line("set \"PYVENV_CFG=%VENV_DIR%\\pyvenv.cfg\"");
    line("set \"NODE_EXE=%HERE%\\node\\node.exe\"");
    line("set \"WEBUI_ENTRY=%HERE%\\webui\\dist\\server\\index.js\"");
    line("set \"WEBUI_PORT=8648\"");
    line("");

    // ---- 沙箱目录 (先建, 再指) ----
    line("rem ---------- 1) sandbox dirs (create BEFORE pointing anything at them) ----------");
    line("for %%D in (");
    line("    \"%SANDBOX%\"");
    line("    \"%DATA_DIR%\"");
    {
        // 目录清单来自 Paths::sandboxVarTable() —— 与 Launcher 注入的环境变量同源
        const auto& table = hs::Paths::sandboxVarTable();
        std::vector<std::string> dirs;
        for (const auto& v : table) {
            if (!v.isDir || v.rel == nullptr || v.rel[0] == '\0') continue;
            std::string rel = v.rel;
            for (auto& c : rel) if (c == '/') c = '\\';
            if (std::find(dirs.begin(), dirs.end(), rel) == dirs.end()) dirs.push_back(rel);
        }
        for (size_t i = 0; i < dirs.size(); ++i) {
            line("    \"%SANDBOX%\\" + dirs[i] + "\"");
        }
    }
    line(") do (");
    line("    if not exist \"%%~D\" mkdir \"%%~D\" >nul 2>&1");
    line(")");
    line("");

    // ---- 环境变量劫持 ----
    line("rem ---------- 2) hermetic env hijack (nothing may escape the box) ----------");
    {
        const auto& table = hs::Paths::sandboxVarTable();
        for (const auto& v : table) {
            std::string name = v.name;
            if (v.rel == nullptr || v.rel[0] == '\0') {
                line("set \"" + name + "=%SANDBOX%\"");
            } else {
                std::string rel = v.rel;
                for (auto& c : rel) if (c == '/') c = '\\';
                line("set \"" + name + "=%SANDBOX%\\" + rel + "\"");
            }
        }
    }
    line("");
    line("rem ---------- 3) Hermes native chain ----------");
    line("set \"HERMES_HOME=%DATA_DIR%\"");
    line("set \"HERMES_PORTABLE_ROOT=%HERE%\"");
    line("set \"HERMES_PORTABLE_MODE=1\"");
    line("set \"HERMES_BIN=%VENV_DIR%\\Scripts\\hermes.cmd\"");
    line("set \"PYTHONIOENCODING=utf-8\"");
    line("set \"PYTHONUTF8=1\"");
    line("");

    // ---- junction 对账 ----
    line("rem ---------- 4) repair _home\\.hermes junction after a move ----------");
    line("rem  The junction target is ABSOLUTE, so copying the package to another");
    line("rem  drive/dir silently breaks it. Re-create it every launch (idempotent).");
    line("set \"LINK=%SANDBOX%\\.hermes\"");
    line("if exist \"%LINK%\\config.yaml\" goto :link_ok");
    line("if exist \"%LINK%\" rmdir \"%LINK%\" >nul 2>&1");
    line("if exist \"%DATA_DIR%\" mklink /J \"%LINK%\" \"%DATA_DIR%\" >nul 2>&1");
    line(":link_ok");
    line("");

    // ---- pyvenv.cfg 绝对化 ----
    line("rem ---------- 5) absolutize pyvenv.cfg home (idempotent) ----------");
    line("if exist \"%PYVENV_CFG%\" (");
    line("    powershell -NoProfile -Command \"& {$p='%PYVENV_CFG%'; $h='%PY_BASE%'; $t=[IO.File]::ReadAllText($p); $t=[regex]::Replace($t,'(?im)^\\s*home\\s*=.*$','home = '+$h); [IO.File]::WriteAllText($p,$t)}\"");
    line(")");
    line("");

    // ---- 校验 ----
    line("rem ---------- 6) bail out early if the box is incomplete ----------");
    line("if not exist \"%NODE_EXE%\" (");
    line("    echo   [ERR] Node not found: %NODE_EXE%");
    line("    goto :eof");
    line(")");
    line("if not exist \"%WEBUI_ENTRY%\" (");
    line("    echo   [ERR] web-ui not found: %WEBUI_ENTRY%");
    line("    goto :eof");
    line(")");
    line("");
    line("echo.");
    line("echo   Hermes Portable");
    line("echo   Root   : %HERE%");
    line("echo   Data   : %DATA_DIR%");
    line("echo   Home   : %SANDBOX%");
    line("echo   Web UI : http://127.0.0.1:%WEBUI_PORT%");
    line("echo.");
    line("");
    line("rem ---------- 7) start web-ui ----------");
    line("start \"\" /b \"%NODE_EXE%\" \"%WEBUI_ENTRY%\" start %WEBUI_PORT%");
    line("echo   Hermes Web UI starting on %WEBUI_PORT% ...");
    line("exit /b 0");

    return o.str();
}

} // namespace hs::portable
